import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SFProDisplay, CabinetGrotesk } from "@/utils/custom-fonts";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Streamify ♫",
  description: `Generated by Nnajiofor Uchenna Franklin",
  keywords: "Streamify is music platform were a user can see the performance 
  of his/her music and also stream latest, favourite and trending musics.`,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${SFProDisplay.variable} ${CabinetGrotesk.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
